name: ron_digital
description: A new Flutter project.



publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"




dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0


  
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  auto_size_text: ^3.0.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  build_runner: ^2.1.10
  hive_generator: ^1.1.2
  path_provider: ^2.0.10
  http: ^0.13.4
  easy_localization: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^1.0.0



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/lang/

